### ISSUE TITLE
Works great until bundling

### ISSUE THREAD

**Issue by ghost** [lorenooliveira/ng-text-truncate#11]
I'm wondering if I am missing something. NgTextTruncate works well until I try to bundle it in Visual Studio. There might be something wrong with the way the dependency injection is set up, but I'm not familiar enough with Angular to see how to fix it. Any guidance would be appreciated.

Error Message:
Error: [$injector:unpr] http://errors.angularjs.org/1.3.15/$injector/unpr?p0=nProvider%20%3C-%20n
    at Error (native)
    at http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:96324
    at http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:112277
    at Object.r [as get](http://localhost.com/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:111249)
    at http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:112351
    at r (http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:111249)
    at Object.u [as invoke](http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:111513)
    at l.instance (http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:131831)
    at http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:123022
    at r (http://localhost/bundles/layout?v=pPQSPzFqGMM9okyxS_3JkET-cIGsTVXxRu8XaUY00O81:1:96813)

Relevant bits of code:

app.js:
var app = angular.module('app', ['ui.bootstrap', 'ngRoute', 'ngTextTruncate']);

app
.controller('controller', controller)
    .directive('routeLoadingIndicator', loadingDirective)
    .directive('errorMessage', displayErrorDirective)
    .factory('seServices', seServices)
    .factory('scService', scService)
    .factory('scSurvey', scSurvey)

var configFunction = function ($routeProvider, $locationProvider, $httpProvider, baseUrl) {
    //Do stuff
}

configFunction.$inject = ['$routeProvider', '$locationProvider', '$httpProvider', 'baseUrl'];

app.config(configFunction);

controller.js:
var controller = function ($scope, $log, $location, $routeParams, baseUrl, scSurvey, searchResults) {
    //Do stuff
}
controller.$inject = ['$scope', '$log', '$location', '$routeParams', 'baseUrl', 'scSurvey', 'searchResults'];

HTML:

<p ng-text-truncate="Description"  ng-tt-words-threshold="40"></p>

Visual Studio Bundles:

bundles.Add(new ScriptBundle("~/bundles/layout").Include(
   "~/Scripts/jquery-1.11.2.min.js",
   "~/Scripts/angular.min.js",
   "~/Scripts/Plugins/ui-bootstrap-tpls.min.js"
));

bundles.Add(new ScriptBundle("~/bundles/test").Include(
    "~/Scripts/angular-route.min.js",
    "~/Scripts/Plugins/ng-text-truncate.js",
    "~/Scripts/service.js",
    "~/Scripts/controller.js",
    "~/Scripts/app.js"
));

**Comment by roger-borges** [comment]
For me the bundling isn't the issue - it's the minification of ng-text-truncate.js that gets in the way. It would be great if lorenooliveira could provide a ng-text-truncate-min.js version

**Comment by liuruting** [comment]
For me too, it is the minification of ng-text-truncate.js that cause an error for https://docs.angularjs.org/error/$injector/unpr?p0=tProvider%20%3C-%20t

Update: Created pull request #12 to fix this issue

**Comment by ghost** [comment]
Thanks for working on a fix, liuruting. I'll have to try it out later, but I appreciate your effort.

**Comment by ghost** [comment]
I finally got back to this. The bundling and minification now works with liuruting's change. Thanks.
